### ISSUE TITLE
Use remove listeners from sdk

### ISSUE THREAD

**Issue by galpressman** [GalPressman/matrigram#1]
Once this code is merged
https://github.com/matrix-org/matrix-python-sdk/pull/78

**Comment by galpressman** [comment]
@YuvalFatael good to go!

**Comment by YuvalFatael** [comment]
[https://github.com/GalPressman/matrigram/commit/5306b5cc54df99fee96065e14debaf62464b6d5d](url)

**Comment by YuvalFatael** [comment]
[5306b5cc54df99fee96065e14debaf62464b6d5d](url)

**Comment by YuvalFatael** [comment]
[5306b5cc54df99fee96065e14debaf62464b6d5d](https://github.com/GalPressman/matrigram/commit/5306b5cc54df99fee96065e14debaf62464b6d5d)

**Comment by galpressman** [comment]
@YuvalFatael you can mention the issue in the commit message, it will auto link it to here.
