### ISSUE TITLE
Handle invites

### ISSUE THREAD

**Issue by galpressman** [GalPressman/matrigram#12]

**Comment by GalPressman** [comment]
Invite event:
22:40:57 DEBUG client@on_invite_event +93: invite event {
    "events": [
        {
            "content": {
                "join_rule": "public"
            }, 
            "sender": "@matrigram1:matrix.org", 
            "state_key": "", 
            "type": "m.room.join_rules"
        }, 
        {
            "content": {
                "avatar_url": null, 
                "displayname": "manish", 
                "membership": "join"
            }, 
            "sender": "@manish:matrix.org", 
            "state_key": "@manish:matrix.org", 
            "type": "m.room.member"
        }, 
        {
            "content": {
                "alias": "#matrigram:matrix.org"
            }, 
            "sender": "@matrigram1:matrix.org", 
            "state_key": "", 
            "type": "m.room.canonical_alias"
        }, 
        {
            "content": {
                "name": "#matrigram:matrix.org"
            }, 
            "sender": "@matrigram1:matrix.org", 
            "state_key": "", 
            "type": "m.room.name"
        }, 
        {
            "content": {
                "avatar_url": null, 
                "displayname": null, 
                "membership": "invite"
            }, 
            "event_id": "$14845128571739608vLDhe:matrix.org", 
            "membership": "invite", 
            "origin_server_ts": 1484512857562, 
            "sender": "@manish:matrix.org", 
            "state_key": "@manish2:matrix.org", 
            "type": "m.room.member", 
            "unsigned": {
                "age": 68, 
                "prev_content": {
                    "membership": "leave"
                }, 
                "prev_sender": "@manish2:matrix.org", 
                "replaces_state": "$14845128501739572XyxVm:matrix.org"
            }
        }
    ]
}

**Comment by galpressman** [comment]
Invite event:
```
22:40:57 DEBUG client@on_invite_event +93: invite event {
    "events": [
        {
            "content": {
                "join_rule": "public"
            }, 
            "sender": "@matrigram1:matrix.org", 
            "state_key": "", 
            "type": "m.room.join_rules"
        }, 
        {
            "content": {
                "avatar_url": null, 
                "displayname": "manish", 
                "membership": "join"
            }, 
            "sender": "@manish:matrix.org", 
            "state_key": "@manish:matrix.org", 
            "type": "m.room.member"
        }, 
        {
            "content": {
                "alias": "#matrigram:matrix.org"
            }, 
            "sender": "@matrigram1:matrix.org", 
            "state_key": "", 
            "type": "m.room.canonical_alias"
        }, 
        {
            "content": {
                "name": "#matrigram:matrix.org"
            }, 
            "sender": "@matrigram1:matrix.org", 
            "state_key": "", 
            "type": "m.room.name"
        }, 
        {
            "content": {
                "avatar_url": null, 
                "displayname": null, 
                "membership": "invite"
            }, 
            "event_id": "$14845128571739608vLDhe:matrix.org", 
            "membership": "invite", 
            "origin_server_ts": 1484512857562, 
            "sender": "@manish:matrix.org", 
            "state_key": "@manish2:matrix.org", 
            "type": "m.room.member", 
            "unsigned": {
                "age": 68, 
                "prev_content": {
                    "membership": "leave"
                }, 
                "prev_sender": "@manish2:matrix.org", 
                "replaces_state": "$14845128501739572XyxVm:matrix.org"
            }
        }
    ]
}
```
