### ISSUE TITLE
Feature Request: Add ability to change the bot's Matrix displayname

### ISSUE THREAD

**Issue by neutralinsomniac** [GalPressman/matrigram#13]

**Comment by YuvalFatael** [comment]
added in a separate branch [set-matrix-name](https://github.com/GalPressman/matrigram/tree/set-matrix-name) for now. we will merge it to master soon.

**Comment by YuvalFatael** [comment]
https://github.com/GalPressman/matrigram/commit/e0f84e1b4b90f7fbf78490322ebd6310114fbdf4

**Comment by galpressman** [comment]
e0f84e1b4b90f7fbf78490322ebd6310114fbdf4
